version: '3.4'

services:
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./config/.env.db
  axiom4-api:
    image: axiom4-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./config/.env.db
      - ./config/.env.app
  axiom4-web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=axiom4.net
      - NGINX_PORT=80
    depends_on:
      - axiom4-api
volumes:
  db:
    driver: local