# Generated by Django 4.2.5 on 2023-09-18 18:36

import ImageUpload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0006_alter_imageupload_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(storage=ImageUpload.models.OverwriteStorage(), upload_to=ImageUpload.models.directory_path),
        ),
    ]
