"""
Django settings for axiom4 project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import re

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


def _csv_env(name, default=""):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


def _list_env(name, default=""):
    raw = os.environ.get(name, default)
    return [item.strip() for item in re.split(r"[\s,]+", raw) if item.strip()]


def _is_ipv4(host):
    return re.fullmatch(r"\d{1,3}(?:\.\d{1,3}){3}", host) is not None


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent

# Load environment variables for all entrypoints (manage.py, ASGI, WSGI, supervisor).
for _env_file in (
    BASE_DIR / ".env",
    PROJECT_ROOT / "config" / ".env.app",
    PROJECT_ROOT / "config" / ".env.db",
):
    if _env_file.exists():
        load_dotenv(_env_file, override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY environment variable is required.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "0") == "1"

ALLOWED_HOSTS = _list_env("DJANGO_ALLOWED_HOSTS", "localhost 127.0.0.1 [::1]")

_host_variants = set(ALLOWED_HOSTS)
for _host in ALLOWED_HOSTS:
    if _host.startswith("www."):
        _host_variants.add(_host[4:])
    elif (
        "." in _host
        and _host not in {"localhost"}
        and not _host.startswith("[")
        and not _is_ipv4(_host)
    ):
        _host_variants.add(f"www.{_host}")
ALLOWED_HOSTS = sorted(_host_variants)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    "corsheaders",
    'martor',
    'Blog',
    'ImageUpload',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'axiom4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'axiom4.wsgi.application'
ASGI_APPLICATION = "axiom4.asgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get("MYSQL_DATABASE"),
        'USER': os.environ.get("MYSQL_USER"),
        'PASSWORD': os.environ.get("MYSQL_PASSWORD"),
        'HOST': os.environ.get("MYSQL_HOST"),
        'PORT': os.environ.get("MYSQL_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = os.environ.get("STATIC_URL", "/static/")
STATIC_ROOT = os.environ.get("STATIC_ROOT", BASE_DIR / "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CSRF_TRUSTED_ORIGINS = _csv_env(
    "CSRF_TRUSTED_ORIGINS",
    "http://127.0.0.1:4200",
)

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = False
CORS_ORIGIN_ALLOW_ALL = False

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'csrftoken',
    'x-requested-with',
]

CORS_ALLOWED_ORIGINS = _csv_env(
    "CORS_ALLOWED_ORIGINS",
    "http://127.0.0.1:4200,http://localhost:4200,http://localhost:4000,http://127.0.0.1:4000",
)

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

USE_X_FORWARDED_HOST = True
SCRIPT_NAME = os.environ.get("SCRIPT_NAME", "/api")
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "0") == "1"
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

MEDIA_ROOT = os.environ.get("MEDIA_ROOT", 'media')
MEDIA_URL = os.environ.get("MEDIA_URL", '/media/')


X_FRAME_OPTIONS = 'DENY'

MARTOR_THEME = 'bootstrap'

MARTOR_ENABLE_CONFIGS = {
    'emoji': 'true',
    'imgur': 'false',
    'mention': 'false',
    'jquery': 'true',
    'living': 'true',
    'spellcheck': 'false',
    'hljs': 'true',
}

MARTOR_MARKDOWNIFY_URL = '/martor/markdownify/'
MARTOR_MARKDOWNIFY_TIMEOUT = 0

MARTOR_UPLOAD_URL = ''

MARTOR_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.nl2br',
    'markdown.extensions.smarty',
    'markdown.extensions.fenced_code',
    'markdown.extensions.sane_lists',
    'martor.extensions.urlize',
    'martor.extensions.del_ins',
    'martor.extensions.emoji',
    'martor.extensions.escape_html',
    'axiom4.markdown_mermaid',
]

# Keep the allowed HTML surface small while preserving Mermaid containers and
# basic markdown formatting.
ALLOWED_HTML_TAGS = [
    "a", "abbr", "b", "blockquote", "br", "cite", "code", "command",
    "dd", "del", "div", "dl", "dt", "em",
    "h1", "h2", "h3", "h4", "h5", "h6",
    "hr", "i", "img", "ins", "kbd",
    "li", "ol", "optgroup", "option", "p", "pre", "small", "span", "strong",
    "sub", "sup", "table", "tbody", "td", "tfoot", "th", "thead", "tr", "u", "ul",
]

ALLOWED_HTML_ATTRIBUTES = [
    "alt", "class", "colspan", "datetime",
    "height", "href", "rowspan", "scope", "src", "title", "width",
]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),
    }
}

ACCESS_LIST = _list_env("ACCESS_LIST", "127.0.0.1")
TRUSTED_PROXY_IPS = _list_env("TRUSTED_PROXY_IPS", "")

REST_FRAMEWORK = {
    # YOUR SETTINGS
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] + (['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else []),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Axiom4.net API',
    'DESCRIPTION': 'API app Axiom4.net',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_PATCH': False,
    'SERVE_URLCONF': 'axiom4.urls',
    'PUBLIC': False,
    'OAS_VERSION': '3.1.1',
    'SERVE_PERMISSIONS': ['axiom4.permissions.AccessListPermission'],
}
