# Generated by Django 4.2.4 on 2023-08-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_tag',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
