# Generated by Django 4.2.4 on 2023-08-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_category_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
