# Generated by Django 4.2.4 on 2023-08-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_rename_category_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
