# Generated by Django 4.2.4 on 2023-08-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_rename_category_post_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
    ]
