# Generated by Django 4.2.5 on 2023-09-18 18:36

import Blog.models.Post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, storage=Blog.models.OverwriteStorage(
            ), upload_to=Blog.models.image_directory_path),
        ),
    ]
