# Generated by Django 6.0.4 on 2026-04-12 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_post_meta_indexes_ordering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_author_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='Blog_post_created_eb568b_idx',
            old_name='blog_post_created_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='Blog_post_author__7655b6_idx'),
        ),
    ]
