# Generated by Django 4.2.4 on 2023-08-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tag',
            field=models.CharField(
                default='about', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(
                fields=['tag'], name='Blog_page_tag_c5298b_idx'),
        ),
    ]
