# Generated by Django 4.2.4 on 2023-08-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_short_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_tag',
        ),
    ]
