# Generated by Django 4.2.4 on 2023-08-23 20:30

import Blog.models.Post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_post_short_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(
                null=True, upload_to=Blog.models.image_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
