# Generated by Django 4.2.4 on 2023-08-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
