# Generated by Django 4.2.4 on 2023-08-19 20:38

import ImageUpload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUpload', '0002_remove_image_filename_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(
                upload_to=ImageUpload.models.directory_path),
        ),
    ]
