/**
 * Axiom4.net API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Category } from '../model/models';
import { Page } from '../model/models';
import { PaginatedPostPreviewList } from '../model/models';
import { Post } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface BlogCategoriesRetrieveRequestParams {
    id: number;
}

export interface BlogPagesRetrieveRequestParams {
    tag: string;
}

export interface BlogPostsListRequestParams {
    categoriesName?: string;
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
}

export interface BlogPostsRetrieveRequestParams {
    id: number;
}


export interface BlogServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * API endpoint that allows groups to be viewed or edited.
*/
    blogCategoriesList(extraHttpRequestParams?: any): Observable<Array<Category>>;

    /**
     * 
     * API endpoint that allows groups to be viewed or edited.
* @param requestParameters
     */
    blogCategoriesRetrieve(requestParameters: BlogCategoriesRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Category>;

    /**
     * 
     * 
*/
    blogPagesList(extraHttpRequestParams?: any): Observable<Array<Page>>;

    /**
     * 
     * 
* @param requestParameters
     */
    blogPagesRetrieve(requestParameters: BlogPagesRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Page>;

    /**
     * 
     * 
* @param requestParameters
     */
    blogPostsList(requestParameters: BlogPostsListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedPostPreviewList>;

    /**
     * 
     * 
* @param requestParameters
     */
    blogPostsRetrieve(requestParameters: BlogPostsRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Post>;

}
